RedHatInsights/insights-remediations

README.md

Update readme Contact session

---

build/Dockerfile

The tests pass for this when I run them against node12. 
Updating the image. This should fix a few things for us.
Signed-off-by: Stephen Adams <tsadams@gmail.com>

update(node): bump to a more recent version of node

---

src/api/openapi.yaml
src/connectors/vmaas/mock.js
src/generator/__snapshots__/package.integration.js.snap
src/generator/package.integration.js
src/issues/index.js
src/remediations/read.integration.js
src/templates/static/patchman/packages.yml
src/util/identifiers.js
src/util/identifiers.unit.js

update of https://github.com/RedHatInsights/insights-remediations/pull/6

Add special chars to regex valiadation

---

src/generator/__snapshots__/package.integration.js.snap
src/generator/package.integration.js

package regex quickfix

---

src/config/index.js
src/connectors/dispatcher/impl.js
src/connectors/dispatcher/impl.unit.js
src/connectors/dispatcher/index.js
src/connectors/dispatcher/mock.js

Added Connector for Playbook Dispatcher along with an initial method for posting run playbook jobs.

RHCLOUD-11402: Create Connector for Playbook Dispatcher

---

src/connectors/vmaas/mock.js
src/generator/__snapshots__/package.integration.js.snap
src/generator/package.integration.js
src/issues/index.js
src/templates/static/patchman/packages.yml

it was failing for numbers and capital letters in rpm package name

updated PKG_PATTERN regex

---

src/generator/__snapshots__/package.integration.js.snap
src/generator/package.integration.js

Quickfix for package test

---

src/config/index.js

quickfix for dispatcher config

---

src/remediations/remediations.format.js

Quickfix based on feedback from Rodrigo's testing.    

Quickfix: update buildRHCUrl

---

src/config/index.js
src/connectors/configManager/impl.js
src/connectors/configManager/impl.unit.js
src/connectors/configManager/index.js
src/connectors/configManager/mock.js

Created config manager connector for upcoming check for "remediations: enabled" state.
JIRA:  https://issues.redhat.com/browse/RHCLOUD-13501

RHCLOUD-13501: Create config manager connector

---

package-lock.json
package.json

Security vulnerability found in prismjs versions less than 1.23.0
RHCLOUD-13306
Signed-off-by: Stephen Adams <tsadams@gmail.com>

[module] update prismjs npm module

---

src/api/openapi.yaml
src/remediations/__snapshots__/fifi.integration.js.snap
src/remediations/controller.fifi.js
src/remediations/fifi.integration.js
src/remediations/fifi.js

Added Config Manager check to remediations execute & pre-flight check logic.
JIRA: https://issues.redhat.com/browse/RHCLOUD-13502

RHCLOUD-13446: Add Config Manager Check to remediations execute & preflight logic

---

src/connectors/configManager/impl.js

Quickfix for config-manager-connector.    

quickfix for config-manager-connector

---

src/generator/__snapshots__/generator.unit.js.snap
src/generator/generator.unit.js
src/resolutions/resolvers/TestResolver.js

Update signature test-playbooks resolver so that the test playbooks can be called.    

Update signature test-playbooks

---

deployment/deploy.yml

We need the deployment file in the repo to properly switch to
app-interface builds and deployments
Signed-off-by: Stephen Adams <tsadams@gmail.com>

[task] add deployment file to repo

---

src/connectors/dispatcher/impl.js

Update dispatcher connector "GET" functions to have the correct hostname.    

[QUICK FIX]: Update dispatcher connector get functions

---

src/connectors/contentServer/impl.js
src/connectors/contentServer/impl.unit.js

workaround for https://issues.redhat.com/browse/ADVISOR-1728

[content-server] filter out playbooks with null play

---

src/connectors/dispatcher/index.js
src/connectors/dispatcher/noop.js

add noop playbook-dispatcher connector

---

src/connectors/dispatcher/impl.js
src/connectors/dispatcher/impl.unit.js

Update URI generation for some of the dispatcher methods.    

[QUICK_FIX]:  Update URI generation for some of the dispatcher methods

---

db/migrations/20210127154038-add-additional-error-fileds.js
src/remediations/models/playbookRunExecutors.js

Added migration for additional error checking code fields

---

deployment/playbooks-ssg.yaml

Signed-off-by: Stephen Adams <tsadams@gmail.com>

[migration] add playbooks-ssg template from saas-templates

---

src/connectors/dispatcher/impl.unit.js
src/connectors/http.js
src/remediations/controller.read.js

[QUICKFIX]: update remediations to not misenterperate  dispatcher responses

[QUICKFIX]: update remediations to not misenterperate  dispatcher responses

---

src/remediations/fifi.js

QUICK FIX for dispatcher/runs fields and success status error.    

QUICKFIX: Fix pushed executor fields & status success error

---

deployment/deploy.yml

Add backoffice host to parameters.    

Add backoffice host to parameters

---

deployment/deploy.yml

Update env vars

---

src/remediations/__snapshots__/fifi.integration.js.snap
src/remediations/fifi.integration.js
src/remediations/fifi.js

In the event that there are no "executorless" systems when the pre-flight check is called.  Remove the empty `no-executor` status field from the returned data.

QUICKFIX: remove empty no executor state from preflight check

---

deployment/deploy.yml

Update PLATFORM_HOSTNAME in stage and prod.    

[QUICKFIX]: Update PLATFORM_HOSTNAME in stage and prod

---

deployment/deploy.yml

[QUICKFIX]: Update platform hostname again.    

[QUICKFIX]: Update platform hostname again

---

deployment/deploy.yml
src/config/index.js

Create Platform-hostname-url env variable.    

Create Platform-hostname-url env variable

---

src/errors.js

Improve internal error messaging for Remediations.
JIRA: https://issues.redhat.com/browse/RHCLOUD-14602

RHCLOUD-14602: Improve internal error messaging for Remediations

---

deployment/deploy.yml

Fix Inventory unavailable in staging.  Add new inventory_port env variable.    

RHCLOUD-14856: Add inventory port to staging env

---

deployment/deploy.yml

Update inventory port var name

---

deployment/clowdapp.yml

Add Env vars to init container

---

deployment/clowdapp.yml

Update parameters blocking

---

deployment/clowdapp.yml

Update clowdapp.yml formating

---

cdappconfig.json
deployment/clowdapp.yml

[QUICKFIX] clowdapp points to the right apps

---

cdappconfig.json
deployment/clowdapp.yml

[QUICK FIX] Update host inventory dependency name

---

cdappconfig.json
deployment/clowdapp.yml

Update endpoints and dependencies to not include advisor (yet)

---

deployment/clowdapp.yml

[QUICK_FIX] Add ENV_NAME var to the parameters list

---

deployment/clowdapp.yml
src/config/index.js
src/templates/static/patchman/packages.yml

[QUICK FIX]  Fix rds ca certs

---

deployment/clowdapp.yml

[QUICKFIX]  Add image tag param

---

deployment/clowdapp.yml

Update clowdapp config again without secrets

---

deployment/clowdapp.yml

Add Backoffice-dummy-secret to clowdapp

---

src/config/index.js

[QUICK FIX}  Update Clowder enabled enviroment var to work correctly

---

deployment/clowdapp.yml
src/config/index.js

Add additional clowdapp changes to clowdapp

---

package-lock.json
package.json
src/config/index.js

Fix clowder enabled var

---

src/config/index.js

[QUICK_FIX] clowderConfig change

---

deployment/clowdapp.yml

Add psk-playbook-dispatcher secret

---

src/config/index.js

fixin index.js

---

src/config/index.js

Update acgConfig change

---

src/config/index.js

Testing with console logs just to be sure

---

src/config/index.js

Remove uneeded CA declaration from bottom of index.js

---

src/config/index.js

Update db config for Clowder

---

src/config/index.js

change clowder ssl to be based on loaded config

---

src/generator/__snapshots__/package.integration.js.snap
src/issues/index.js
src/templates/static/patchman/packages.yml

Adapted regex from source code of libdnf. Should allow thbrough a few packages which are currently not

Update the NEVRA regex used by patch-package issue handler

---

src/generator/__snapshots__/errata.integration.js.snap
src/generator/errata.integration.js

Update Errata integration tests

---

src/config/index.js

Pull log group from ACG config for clowder deployment

---

src/config/index.js

Update cloudwatch configs for stage

---

deployment/clowdapp.yml
src/config/index.js

[QUICKFIX] update-clowdapp-based-on-errors-in-stage

---

deployment/clowdapp.yml
src/config/index.js

Update clowder dependency hosts

---

deployment/deploy.yml

Add RBAC port var

---

deployment/clowdapp.yml
src/config/index.js

Additional clowder fixes

---

deployment/clowdapp.yml

update compliance host for clowder

---

src/app.js
src/config/index.js

Update remediations port config

---

deployment/clowdapp.yml

Update liveness and readiness port

---

deployment/clowdapp.yml

Fix receptor-controller hostname in staging

[QUICKFIX] Fix receptor-controller hostname in staging

---

src/config/index.js

Add private dependency endpoints to config

---

deployment/clowdapp.yml

[QUICKFIX]  Small updates to clowdapp.yml

---

deployment/clowdapp.yml

[QUICKFIX]  Additional changes to clowdapp parameters

---

build/Dockerfile

Update Dockerfile to explicitly pull latest image

---

build/Dockerfile

Update dockerfile to use nodejs12

---

src/config/index.js

[QUICKFIX] Add testing log for vulnerabilities endpoint

---

src/config/index.js

Fix vuln clowder host

---

src/resolutions/resolvers/SSGResolver.js
src/resolutions/resolvers/SSGResolver.unit.js

[QUICKFIX] Add ssg fallback profile back in

---

src/connectors/compliance/impl.js

[QUICKFIX] Update Compliance caching key to fix cert-auth call

---

deployment/clowdapp.yml
src/config/index.js

Signed-off-by: Victor M <vmugicag@redhat.com>

[QUICKFIX] Amend Compliance clowder component name

---

src/connectors/patchman/mock.js
src/generator/__snapshots__/errata.integration.js.snap
src/generator/__snapshots__/generator.unit.js.snap
src/generator/__snapshots__/patchman.integration.js.snap
src/generator/patchman.integration.js
src/issues/index.js
src/remediations/playbook/__snapshots__/playbook.integration.js.snap
src/remediations/playbook/playbook.integration.js
src/templates/static/patchman/errata.yml

Add support for EPEL-....  adivsories for patch issues

---

src/config/index.js

modify patchman clowder endpoint in config

---

src/config/index.js

Change patchman host again

---

src/config/index.js

Add inventory clowder debug

---

deployment/clowdapp.yml

Update patchman port

---

package-lock.json
package.json
src/config/index.js

Update app common js lib

---

src/api/openapi.yaml

Update spec to help jaudet

---

deployment/clowdapp.yml

QUICKFIX:  Update patchman port prod

---

src/config/index.js

Another quick fix for prod cuz patch CLOWDER is not ready

---

src/config/index.js

Update patch now that it's clowderized in prod

---

src/config/index.js

QUICKFIX: Update vuln clowder hostname

---

src/config/index.js

Update vmaas hostname prod

---

src/config/index.js

Update vuln service connectors to point at clowder deps in prod

---

dashboards/grafana-dashboard-insights-remediations-general.configmap.yaml

[QUICKFIX]:  Update Grafana dasboard with new pannel

---

src/config/index.js

[QUICKFIX]: Update compliance backend service name

---

build_deploy.sh

Update the build_deploy.sh remediation file to actually point to the correct quay repo.
JIRA:  https://issues.redhat.com/browse/RHCLOUD-16747

Update build-deploy.sh with fixing changes

---

deployment/clowdapp.yml

https://github.com/RedHatInsights/clowder/pull/537/files

web: true is deprecated, webServices is current

---

deployment/clowdapp.yml

Update receptor-controller dependency

---

README.md

Update Remediations README with updated instructions for local development.

Quickfix: Update Remediations README

---

src/api/openapi.yaml
src/connectors/inventory/mock.js
src/errors.js
src/remediations/controller.read.js

Add org id query to remediations/{id}/playbook endpoint

---

src/resolutions/resolutions.unit.js
src/routes.js

Added cert-auth support to /remediations/v1/resolutions endpoint to support satellite usage

Resolutions cert auth

---

src/remediations/__snapshots__/fifi.integration.js.snap
src/remediations/controller.read.js
src/remediations/fifi.integration.js
src/remediations/fifi.js

Removed Smart Management checks from the RHC portion of the FiFi pipeline.  
Based on a ticket from Katherine it has been decided that the RHC portion of the FiFi pipeline should no longer be dependent on the smart_management entitlement.  This decision was made in order to support any customer with a RHEL subscription being able to run remediation playbooks on their systems.  In this way the platform would leverage better adoption of both RHC as well as Red Hat Insights.  Additionally with this change (and after conersation with Katheryn and Christian) it was decided that the labeling of "Marketplace" systems would also be depricated such that all "runnable" RHC systems would be sorted into a single Direct Connected group. 
The majority of this work revolved around removing the …

Remove smart-management check from RHC pipeline in Remediations

---

deployment/clowdapp.yml

Update Remediations clowdapp dependencies

---

src/connectors/dispatcher/impl.js
src/connectors/dispatcher/impl.unit.js
src/connectors/dispatcher/mock.js
src/connectors/inventory/mock.js
src/connectors/sources/impl.js
src/connectors/sources/impl.unit.js
src/connectors/sources/mock.js
src/remediations/__snapshots__/fifi.integration.js.snap
src/remediations/controller.fifi.js
src/remediations/fifi.integration.js
src/remediations/fifi.js
src/remediations/fifi.unit.js
src/test/index.js

Update the Remediations pre-flight check to support the Satellite-RHC use case.
With the recent initiative for the shift from receptor to RHC we need to adapt Remediaions to now support 3 main use cases instead of the previous two:
1. Satellite (Receptor)
2. Satellite (RHC)
3. RHC (Direct Connected Systems)
This change has been implemented through the following steps:
1.  Add `/recipient/status` endpoint to the playbook-dispatcher connector to get the status of rhc_clients.
2. Added mock impl for `/recipient/status` for testing purposes
3. Add `/get_rhc_connections` endpoint to sources connector to get the `rhc_client_id` for Satellite-RHC executors.
4. Add `org_id` param from identity header for dispatcher requests
5. Added logic in fifi.js for the Sat-RHC use case without upsetting the …

RHCLOUD-17416: Update Pre-Flight check to support Sat-RHC

---

src/connectors/dispatcher/impl.js
src/remediations/fifi.js

Update dispatcher URI

---

src/connectors/dispatcher/impl.js
src/connectors/dispatcher/impl.unit.js

add change to remediations to account for dispatcher response format

---

src/remediations/fifi.js

Fix preflight empty executor

---

src/remediations/fifi.js

Update preflight with fix for 500 error codes in stage

---

src/connectors/dispatcher/impl.js

Fix dispatcher internal URI calls

---

src/connectors/dispatcher/impl.js
src/remediations/fifi.js

Update log messages for dispatcher to figure out problem

---

src/remediations/fifi.js

Update rhcSatellite definition logic to work if there are no RHC Satellites defined for the remediation

---

src/remediations/fifi.js

Update org-id to be a string when sending it to dispatcher

---

src/remediations/fifi.js

Update dispatcher status request

---

src/remediations/__snapshots__/fifi.integration.js.snap
src/remediations/fifi.integration.js
src/remediations/fifi.js

Add back in Smart Management check to the remediations RHC Direct Connect pipeline.

Add Smart Management Check Back in

---

src/connectors/sources/impl.unit.js
src/connectors/sources/mock.js
src/remediations/fifi.js

Fix getRhcConnections sources endpoint in Remediations.

[QUICKFIX] Fix getRhcConnections sources endpoint in Remediations

---

src/remediations/fifi.js

Update logging for rhc satellite pre flight error.    

[QUICKFIX]: Update logging for rhc satellite pre flight error

---

src/remediations/fifi.js

Update logging again for error fixes.    

Update logging again for error fixes

---

src/connectors/sources/mock.js
src/remediations/fifi.js

Quickfix: update sources check    

Quickfix: update sources check

---

src/remediations/fifi.js

update dispatcher call logging

---

src/connectors/dispatcher/impl.js

Add additional logging

---

src/connectors/dispatcher/impl.js
src/remediations/fifi.js

Fixed a silly copy-and-paste error in a log statement.

Fixed error in log statement.

---

src/connectors/dispatcher/impl.js

Removed /api segment from url for playbook dispatcher v2/dispatch url

---

src/api/openapi.yaml
src/remediations/fifi.js

Also made first_name and last_name optional fields in returned status objects.

Fixed POST body format for playbook dispatcher /internal/v2/dispatch

---

src/remediations/remediations.format.js

QUICKFIX: Update sat_org_id to be a string

---

src/remediations/fifi.js
src/remediations/remediations.format.js

[QUICKFIX] Fixed code to prevent null ansible_hostname

---

src/connectors/dispatcher/impl.js

Added logging of deatils for POST to playbook dispatcher v2/dispatch

---

src/remediations/controller.fifi.js
src/remediations/fifi.js

Restoring some really misleading code so things will work again.

---

src/remediations/fifi.js

Fixed another incorrect status source

---

src/remediations/fifi.js

Another round of trying to keep the status from being 'timeout'

---

src/remediations/fifi.js

We really need to just add this to the list of allowed status types
in the swagger spec and see if the UI will handle it gracefully...

Fixed another silly status=timeout issue.

---

src/connectors/dispatcher/impl.js
src/middleware/identity/identity.unit.js
src/middleware/identity/impl.js
src/middleware/identity/utils.js
src/remediations/fifi.integration.js
src/test/index.js
src/whoami/whoami.controller.js

org_id migration #1

---

deployment/clowdapp.yml
src/connectors/dispatcher/impl.js
src/middleware/identity/identity.unit.js
src/middleware/identity/impl.js
src/middleware/identity/utils.js
src/remediations/fifi.integration.js
src/test/index.js
src/whoami/whoami.controller.js

Org id migration

---

src/config/index.js
src/connectors/bop/impl.js
src/connectors/bop/impl.unit.js
src/connectors/bop/index.js
src/connectors/bop/mock.js
src/status/status.controller.js

Added backoffice proxy connector for tenant org id translation services

---

src/connectors/bop/impl.js

Added temp debug statements to bop connector

---

src/connectors/bop/impl.js

Fixed BOP url

---

deployment/clowdapp.yml

Added TENANT_TRANSLATOR_HOST and TENANT_TRANSLATOR_PORT to clowdapp.yml

---

deployment/clowdapp.yml
src/connectors/bop/impl.js
src/connectors/bop/impl.unit.js
src/connectors/users/impl.js

Unit tests for backoffice proxy connector

---

deployment/clowdapp.yml

Added Migration command parameter to clowdapp.yml to fix issue with migrations not propagating.

Add Migration command parameter to clowdapp.yml

---

db/migrations/20220825014939-populate-tenant_org_id.js
src/connectors/bop/impl.js
src/connectors/bop/mock.js

Tenant org_id migration - db migrations

---

db/migrations/20220825014939-populate-tenant_org_id.js
deployment/clowdapp.yml
src/connectors/bop/impl.js
src/connectors/bop/mock.js

Fix init pod environment

---

src/connectors/bop/impl.unit.js

Meaningless change to trigger a new deployment

---

src/connectors/bop/impl.js
src/connectors/bop/migrate.js

Fixed BOP connector to support db migration

---

deployment/clowdapp.yml

Removed TENANT_TRANSLATION_PORT override

---

src/connectors/bop/impl.js
src/middleware/identity/impl.js

Added org_id to req.user object

---

src/remediations/models/playbookArchive.js
src/remediations/models/remediation.js

Updated sequelize model objects to reflect new tenant_org_id columns

---

db/migrations/20220825014939-populate-tenant_org_id.js

Changed migration to support chunking

---

db/migrations/20220825014939-populate-tenant_org_id.js

Reduced chunk size in migration

---

src/config/index.js

----
- Updating references from the old 3scale dev deployment `apicast.3scale-dev.svc.cluster.local` to the new 3scale dev deployment `gateway.3scale-dev.svc.cluster.local`
- The reason for this change is the Infrastructure Team has stood up a new 3scale (Gateway) Deployment to support service serving certificates. Currently, both the old and new deployments are running in parallel so we can aid workstream in the change over.    
----

Update ref to 3Scale Dev Deployment

---

src/generator/generator.controller.js
src/remediations/playbook/__snapshots__/playbook.integration.js.snap

[REMEDY-85] Fixed post-run logic for RHC-direct targets

---

db/seeders/20181123074644-tests-write.js
src/admin/admin.integration.js
src/api/openapi.yaml
src/connectors/users/mock.js
src/errors.js
src/remediations/__snapshots__/write.integration.js.snap
src/remediations/controller.write.js
src/remediations/routes.js
src/remediations/write.integration.js
src/test/index.js

Remedy 133 bulk delete

---

src/remediations/__snapshots__/write.integration.js.snap
src/remediations/controller.write.js
src/remediations/write.integration.js

REMEDY-133 Allow duplicate IDs in bulk delete

---

src/api/openapi.yaml
src/remediations/__snapshots__/write.integration.js.snap
src/remediations/controller.write.js
src/remediations/write.integration.js

REMEDY-133: Changed bulk delete request payload format

---

db/migrations/20200324133857-job-id-tweaks.js
db/migrations/20200327113936_playbook_run_cascade.js
package-lock.json
package.json
src/db/index.js
src/remediations/remediations.queries.js

REMEDY-244: upgrade to sequelize v6

---

db/seeders/20181123074644-tests-write.js
package-lock.json
package.json
src/api/openapi.yaml
src/remediations/__snapshots__/write.integration.js.snap
src/remediations/controller.write.js
src/remediations/write.integration.js

REMEDY-252 Make bulk delete idempotent

---

.gitignore
CODEOWNERS
README.md
build/Dockerfile
build/docker-compose-unit_test.yml
gulpfile.js
jest.config.js
package-lock.json
package.json
unit_test.sh

Remedy-254: containerize builds

---

build/Dockerfile

REMEDY-254: Fix image

---

build/Dockerfile

REMEDY-254: fix container init failures

---

build/Dockerfile

FIX: Clear npm cache to fix 243 errors

---

build/Dockerfile

Upgrade image npm

---

.npmrc
build/Dockerfile
gulpfile.js

FIX: Move npm cache dir

---

src/connectors/vulnerabilities/impl.js

REMEDY-264 Status check fails for large number of vulnerable systems

---

deployment/clowdapp.yml
src/config/index.js

REMEDY-269: Change user for status check

---

deployment/clowdapp.yml

Added temp command to print userid from init container

---

build/Dockerfile
deployment/clowdapp.yml

REMEDY-274 / REMEDY-275 Build image as non-root and remove init debug.

---

build/Dockerfile

REMEDY-276: Updated parent image

---

src/connectors/testUtils.js
src/connectors/users/impl.js
src/connectors/users/impl.unit.js

REMEDY-269: Use req.identity.user.username for BOP connectivity check

---

package-lock.json

REMEDY-291: Update loader-utils to v1.4.2

---

build/Dockerfile

Upgrade parent image to ubi-minimal:8.7-1049

---

build/Dockerfile

Attempting to fix .npm permissions problem

---

src/probes.js

REMEDY-299: Fixed reference to missing username in playbookGenerated probe

---

src/probes.js

REMEDY-299: Guessed wrong about identity header format for cert-auth

---

src/probes.js

REMEDY-299: same issue with user.email

---

src/generator/generator.controller.js

REMEDY-304: Fix reference to missing req.user in storePlaybookDefinition

---

src/generator/generator.controller.js

Second attempt to fix bad reference to missing req.user

---

build/Dockerfile

Change group ownership of app root

---

deployment/clowdapp.yml
src/config/index.js
src/connectors/bop/impl.js
src/connectors/users/index.js
src/connectors/users/noop.js

Create noop implementation of User connector for back office-less deployments

---

src/config/index.js

Change urls to use https and CA cert to path.

---

deployment/clowdapp.yml

Update XJOIN_HOST_URL to be the correct value, using the pre-defined XJOIN_SEARCH_HOST and XJOIN_SEARCH_PORT values.

Update XJOIN_HOST_URL to be the correct value

---

build/Dockerfile
src/config/index.js

Set NODE_EXTRA_CA_CERTS in Dockerfile CMD

---

package-lock.json
package.json

REMEDY-312: Resolve CVE-2022-37601

---

build/docker-compose-unit_test.yml
build/docker-compose.yml
package.json

REMEDY-325 Add db readiness check to compose files and remove manual delay

---

.github/dependabot.yml

REMEDY-230: Add dependabot update checker for dockerfile parent image

---

build/Dockerfile

Update registry url for Dockerfile parent image

---

package.json
src/api/openapi.yaml
src/remediations/routes.js

REMEDY-332: Remove nullable attributes from run status in swagger spec

---

src/remediations/controller.read.js
src/util/trace.js

Log trace info to help debug performance problem with REMEDY-318

---

src/remediations/controller.read.js

Added additional tracing

---

src/remediations/controller.read.js
src/remediations/fifi.js

Debug tracing

---

src/remediations/controller.read.js
src/util/trace.js

Added elapsed time calculations

---

src/remediations/controller.read.js
src/util/trace.js

Improve performance of REMEDY-318

---

src/remediations/controller.read.js
src/remediations/fifi.js
src/util/trace.js

Adjusted tracing code slightly

---

src/remediations/controller.read.js

Add iteration number to playbook_runs object

---

src/remediations/controller.read.js
src/remediations/fifi.js
src/util/trace.js

Improved tracing of parallel execution

---

src/api/openapi.yaml
src/remediations/controller.read.js
src/remediations/read.integration.js
src/remediations/remediations.format.js

Corrected playbook run formatting for REMEDY-318

---

build/Dockerfile
build_deploy.sh

Update UBI minimal base image to be 1107 as base as well as adding a tag trigger for the security-compliance branch.   

Update UBI minimal base image & add security-compliance tag trigger

---

build_deploy.sh

Update build_deploy spacing error.

Update build_deploy spacing error

---

build/Dockerfile
build_deploy.sh
src/config/index.js

Security compliance

---

deployment/clowdapp.yml

REMEDY-333: Add additional table contents to exported floorist data

---

src/generator/__snapshots__/errata.integration.js.snap
src/generator/__snapshots__/generator.unit.js.snap
src/generator/__snapshots__/package.integration.js.snap
src/generator/__snapshots__/patchman.integration.js.snap
src/remediations/__snapshots__/read.integration.js.snap
src/remediations/playbook/__snapshots__/playbook.integration.js.snap
src/remediations/playbook/playbook.integration.js
src/templates/static/patchman/errata.yml
src/templates/static/patchman/packages.yml
src/templates/static/vulnerabilities/cves.yml

remove from vulnerability and patchman templates
originally introduced by 309849ca2dcc06e25fa1260842d3bc792f32dd8a

warn parameter removed in ansible-core 2.14

---

src/util/log.js

Switch back to using toString() to log trace messages

---

src/remediations/fifi.js

Tidy up trace data

---

src/remediations/controller.fifi.js
src/remediations/fifi.js
src/remediations/routes.js

Remedy-279: Remediation runner filtering

---

src/remediations/fifi.js

Add tracing to connection_status endpoint

---

src/generator/plays/ResolutionPlay.js
src/templates/static/special/headerSimple.yml

RHINENG-717: handle multi-line titles

---

src/util/trace.js

REMEDY-384: Fix trace message formatting

---

src/generator/generator.controller.js
src/generator/routes.js
src/remediations/fifi.js
src/routes.js

REMEDY-363: Add trace data to POST /playbook route.

---

src/connectors/vmaas/vmaas.js
src/generator/factories/CVEFactory.js
src/generator/generator.controller.js
src/resolutions/resolvers/CVEResolver.js

REMEDY-363: Added more tracing

---

src/util/trace.js

Increase latency trigger for trace data to 1 second

---

src/util/log.js

REMEDY-388: added log stream error handler

---

src/connectors/vmaas/vmaas.js
src/util/log.js

REMEDY-388: Reduce trace data volume

---

build/Dockerfile

Upgraded ubi8-minimal parent image

---

src/remediations/fifi.js

REMEDY-379: Check for empty results returned from sources

---

src/util/log.js

REMEDY-388: Tweaked trace data length restriction code

---

src/util/log.js

REMEDY-388: Fixed message size calculation

---

src/util/log.js

REMEDY-389: Fixed missing var in log code

---

src/util/log.js

REMEDY-389: Still trying to figure this out!

---

src/util/log.js

REMEDY-389: Final fix

---

deployment/clowdapp.yml

REMEDY-809: fixed typo in FLOORIST_DB_SECRET_NAME

---

src/config/index.js
src/connectors/dispatcher/impl.js
src/remediations/controller.fifi.js
src/remediations/fifi.js
src/remediations/remediations.format.js

REMEDY-395: Chunk requests to playbook-dispatcher

---

src/connectors/dispatcher/impl.js
src/connectors/dispatcher/impl.unit.js

REMEDY-395: added tests and fixed results aggregation

---

src/config/index.js
src/connectors/vulnerabilities/impl.js
src/connectors/vulnerabilities/impl.unit.js

REMEDY-314: paginate calls to vulnerabilities

---

src/connectors/vulnerabilities/impl.js

REMEDY-314: Adding debug trace

---

src/connectors/vulnerabilities/impl.js

REMEDY-314: Fixed next url for pagination

---

src/connectors/vulnerabilities/impl.js

REMEDY-314: Handle terminal case of pagination

---

src/connectors/vulnerabilities/impl.js

REMEDY-314: Remove temp trace messages

---

src/connectors/dispatcher/impl.js
src/connectors/inventory/systemDetailsBatch.json
src/remediations/fifi.js
src/remediations/remediations.queries.js

REMEDY-398: add pagination support to playbook_dispatcher connector

---

src/connectors/dispatcher/impl.js

REMEDY-398: Fix bad merge code

---

src/remediations/fifi.js

REMEDY-398: Added debug logging for large remediations

---

src/connectors/dispatcher/impl.js
src/connectors/dispatcher/noop.js
src/remediations/fifi.js

REMEDY-410: Chunk playbook dispatcher recipient status requests

---

src/connectors/dispatcher/impl.js

REMEDY-410: Fixed silly recursion copy pasta

---

src/remediations/controller.fifi_2.js
src/remediations/fifi_2.js

Added parameter validation and debug statement

Add check for empty results from playbook-dispatcher status endpoint

---

src/remediations/controller.fifi_2.js

Add debug logging to connection_status endpoint

---

src/middleware/identity/userIdentity.js

Added support for authentication via service account

RHINENG-5482 - Add support for service accounts

---

src/middleware/identity/userIdentity.js

RHINENG-5482: Fixed silly error in identity header processing.

RHINENG-5482 Fixed error in identity header handling

---

src/remediations/remediations.format_2.js

Fixed bad status type and incorrect system count for connection_status endpoint

Fixed bad status type and system count for connection_status

---

src/remediations/controller.read.js

Added temp debug logging for playbook download failure

Debug logging

---

src/remediations/fifi.js
src/remediations/routes.js

More playbook download debug code

Playbook download debug code

---

src/remediations/controller.read.js

More playbook download endpoint debugging.

Debug playbook download endpoint

---

src/remediations/controller.read.js
src/remediations/remediations.format_2.js

The 'localhost' query parameter was overwriting the 'hosts=' parameter...

RHINENG-2835: Fixed malformed playbook download url

---

src/remediations/fifi_2.js
src/remediations/remediations.format_2.js

system_id was missing from playbook dispatcher work requests for rhc-direct systems.

RHINENG-7766: Added system_id to rhc-direct work request for playbook dispatcher

---

src/remediations/remediations.format_2.js

This step 1 of patching around a playbook-dispatcher API bug

RHINENG-7766: Workaround for RHCLOUD-30669 (dispatch bug)

---

src/remediations/remediations.format_2.js

More experimental workarounds of RHCLOUD-30669

RHINENG-7766: Attempting to label playbook runs with inventory id

---

src/remediations/__snapshots__/fifi.integration.js.snap
src/remediations/fifi.integration.js
src/remediations/routes.js

Revert to old connection_status code.

Revert connection_status code changes

---

src/connectors/configManager/impl.js
src/connectors/configManager/impl.unit.js
src/connectors/configManager/mock.js
src/remediations/fifi.integration.js
src/remediations/fifi.js
src/remediations/fifi_2.js

chore: RHINENG-8228 Update config manager API from V1 to V2

---

src/api/openapi.yaml

Updated base url in OpenAPI spec

RHINENG-5465: Fix base url in openAPI spec

---

src/generator/__snapshots__/ssg.integration.js.snap
src/generator/generator.controller.js
src/remediations/playbook/__snapshots__/playbook.integration.js.snap
src/remediations/playbook/playbook.integration.js

RHINENG-4918: Move generateReport play before reboot play

---

src/remediations/fifi_2.js

Nothing to see here - just removing a spurious "new" 😬

RHINENG-8700: Removed a spurious "new"

---

src/remediations/controller.fifi.js

Fixed null reference I playbook run cancel code.

RHINENG-8732: Fix null reference error in playbook run cancel code

---

.gitignore
src/api/openapi.yaml
src/db/index.js
src/remediations/__snapshots__/fifi.integration.js.snap
src/remediations/fifi.integration.js
src/remediations/fifi_2.js

POST /api/remediations/v1/remediations/:id/playbook_runs {exclude: ['rhc']} is now case-insensitive

RHINENG-8733: Made rhc exclude keyword case-insensitive and added tests

---

src/remediations/remediations.queries.js

Add some additional tracing so we can diagnose an internal server error in prod (since it happens reliably for a customer there but we are unable to reproduce in stage).

RHINENG-8757: Added some additional tracing for debug in prod

---

package-lock.json
package.json
src/remediations/controller.read.js

Upgrade to a less ancient version of openapi-default-setter and remove workaround code for nested defaults bug.

RHINENG-8950: Upgrade openapi-default-setter

---

src/connectors/dispatcher/impl.js
src/connectors/dispatcher/test.js_save

Added code to split connection status requests into chunks of 50 systems max.

RHINENG-9083: Added code to chunk dispatcher connection_status requests.

---

src/connectors/dispatcher/impl.js
src/connectors/dispatcher/test.js_save

Fixed silly errors in dispatcher connection status chunking logic.

RHINENG-9083

---

src/connectors/dispatcher/impl.js

Adding some debug logging for dispatcher connection status results

RHINEG-4876: Added debug logging for dispatcher connection status results

---

src/connectors/dispatcher/impl.js

RHINENG-4876: fixed typo in log statement

---

src/connectors/dispatcher/impl.js

Ugh - my IDE automatically added an erroneous 'require'...

RHINENG-4876: Deleting import IDE erroneously added

---

src/connectors/dispatcher/impl.js

Added additional debug logging

RHINENG-4876: Additional debug logging

---

src/connectors/dispatcher/impl.js
src/remediations/controller.fifi_2.js

Collating function for dispatcher status requests had a context binding issue

RHINENG-4876: Fixed promise context binding problem in connection status collation code

---

src/connectors/dispatcher/__snapshots__/impl.unit.js.snap
src/connectors/dispatcher/impl.js
src/connectors/dispatcher/impl.unit.js
src/connectors/dispatcher/serviceMock.js
src/connectors/inventory/impl.unit.data.js
src/connectors/inventory/systemGenerator.js
src/remediations/fifi.integration.js

There was an unhandled edge case in the code that reassembles chunked connection status requests.  This PR fixes that problem and improved tests to cover this condition.

RHINENG-9095: Added robust tests for connection status collation.

---

build/Dockerfile
package-lock.json
package.json

Resolving 'critical' npm audit items and updating ubi-8 parent image

RHINENG-9231: Updating misc npm packages and ubi base image for security vulnerabilities

---

package-lock.json
package.json

Updating sequelize, partly to address a mysterious deployment failure but also because it's due...

Updated sequelize

---

package-lock.json
package.json

Looks like the newest version app-common-js is causing a deployment error (?)

Regressing app-common-js to diagnose deployment error

---

package-lock.json
package.json

Updated various packages to resolve vulnerabilities.

RHINENG-9153: Various package updates

---

.dockerignore
.gitignore
build/Dockerfile
build/docker-compose-unit_test.yml
gulpfile.js

Update the way we build the image for remediations.

RHINENG-9528: Improve image build process

---

src/api/openapi.yaml
src/connectors/dispatcher/impl.js
src/connectors/dispatcher/mock.js
src/remediations/__snapshots__/fifi.integration.js.snap
src/remediations/fifi.integration.js
src/remediations/remediations.format_2.js

Fixed the connection_status to correctly report system counts by connect status type for direct-connected systems.

RHINENG-9584: Fix connection status aggregation

---

src/api/openapi.yaml
src/remediations/controller.read.js
src/remediations/read.integration.js
src/remediations/remediations.format.js
src/remediations/remediations.queries.js

RHINENG-9666: List remediation plan names by org id

---

src/util/trace.js

Quick fix for crash looping pods 😬

Limit size of trace array

---

src/remediations/controller.read.js
src/util/log.js

More attempts to isolate source of overly large cloudwatch messages

Reordered name list generation

---

src/api/openapi.yaml
src/remediations/write.integration.js

Remediation plan name regex didn't support single character plan names.

Fixed regex for remediation plan name

---

src/api/openapi.yaml
src/remediations/write.integration.js

Just restoring the previous regex...

RHINENG-9857: restoring regex to disallow leading/trailing whitespace

---

db/migrations/20240605184623-trim-nbsp-from-plan-names.js

RHINENG-10519: Fix remediation plan names with nbsp

---

deployment/clowdapp.yml

feat(metrics): collect more metrics

---

package-lock.json
package.json

RHINENG-11184: Bump ioredis and debug

---

package-lock.json

RHINENG-11258: Bump es5-ext from 0.10.62 to 0.10.64

---

build/Dockerfile

RHINENG-11284: Bump npm from 10.5.2 to 10.8.1

---

deployment/clowdapp.yml

fix(floorplan): force TEXT type for some UUID columns

---

src/connectors/ssg/impl.js

Nothing to see here, just adding some trace statements to help debug a compliance playbook generation issue...

RHINENG-11246: Added some debug tracing

---

build/Dockerfile
unit_test.sh

Fix failing builds caused by podman-compose issues.

Unit test script rewrite

---

src/remediations/controller.read.js

Just adding some tracing statements to help debug a playbook generation timeout bug.

Playbook generation debug tracing

---

src/remediations/playbook/routes.js

Enable tracing for the playbook download endpoint.

RHINENG-11246: enable tracing for playbook download endpoint

---

deployment/clowdapp.yml

Fixing deplyment issue

---

build/docker-compose.yml
src/connectors/http.js
src/connectors/ssg/impl.js

Extended the REDIS caching code to support transformed non-JSON data (compliance-ssg returns raw yaml).

RHINENG-11246: Fixed caching to support non-JSON data

---

build/docker-compose.yml
package.json
src/config/__snapshots__/config.unit.js.snap
src/config/index.js
src/remediations/controller.read.js
src/remediations/controller.status.js
src/remediations/remediations.queries.js

Adding caching for db remediation plan queries to reduce the concurrent load on the database.

RHINENG-11246: Added caching for remediation plan db query.

---

db/migrations/20240820140920-add-index-on-issue-resolution.js
src/remediations/remediations.queries.js

Improving SQL query for fetching remediation plan by optimizing. issue count sub-select and adding a table index.

RHINENG-11246: Fixed inefficient SQL issue count sub-select and added db index

---

src/generator/generator.controller.js

Just cleaning up some old debug trace statements that are clogging up the logs a bit...

RHINENG-12324: Removed extraneous trace data

---

deployment/clowdapp.yml

fix(deployment): remove unused app dependency

---

dashboards/grafana-dashboard-insights-remediations-general.configmap.yaml

* upgrades old graphs to new Timeseries
* fixes CPU and Memory charts
* improves labeling
* removes Redis and SSG panels

fix(grafana): update and fix dashboard

---

dashboards/grafana-dashboard-insights-remediations-general.configmap.yaml

Adds graph for tracking Playbook Dispatcher's validation failures and errors to Grafana dashboard.

feat(grafana): plot PD validation failures and errors

---

dashboards/grafana-dashboard-insights-remediations-general.configmap.yaml

fix(grafana): FiFi layout

---

deployment/clowdapp.yml

Request PostgreSQL version 14 (mainly used in ephemeral).
Fixes deployment on ephemeral.

chore(deloy): request PG 14

---

build/Dockerfile

RHINENG-12539: Migrate from ubi8-minimal to ubi9-minimal

---

deployment/clowdapp.yml

chore(clowdapp): add cloud-connector to opt deps

---

deployment/clowdapp.yml

chore(clowdapp): add mosquitto MQTT to opt deps

---

package-lock.json
package.json

RHINENG-12414: Update sinon to 19.0.2

---

LICENSE
package.json

RHINENG-13423: Added a LICENSE file 😬

Add LICENSE file

---

deployment/clowdapp.yml

Consume quay image from the konflux repo

---

package-lock.json
package.json

Added a version override for the async package to mitigate a security vulnerability.

RHINENG-11289: Added override for Async package version

---

build/docker-compose-unit_test.yml
build/docker-compose.yml
deployment/clowdapp.yml
unit_test.sh

RHINENG-13722: Upgrade db image to postgresql-rds:16

---

.tekton/remediations-backend-pull-request.yaml
.tekton/remediations-backend-push.yaml

feat(konflux): update buildah to support subscriptions

---

build/Dockerfile

RHINENG-13907: Rollback remediations to ubi8-minimal

---

.tekton/remediations-backend-pull-request.yaml
.tekton/remediations-backend-push.yaml

RHINENG-14068: add new mandatory RPM signature scan task to tekton

---

package-lock.json
package.json

Added override for the execa pacakge to fix a cross-spawn vulnerability.

RHINENG-14279: override execa to fix cross-spawn package vulnerability

---

build/Dockerfile

RHINENG-14308: Upgrade rpm packages

---

src/generator/factories/CVEFactory.js
src/generator/generator.controller.js

Reduced the excessive amount of trace data we record for Patch issues.

RHINENG-14707: Reduce trace data for Patch issues

---

package-lock.json
package.json

Moving to express 4.21.2 to address CVE-2024-52798

RHINENG-14736: update express to 4.21.2

---

build/Dockerfile

RHINENG-12600: Migrate from ubi8-minimal to ubi9-minimal

---

doc/diagrams/v1/remediations/{plan_id}/playbook_runs/getRunDetails.md
doc/responses/remediations/single_playbook_run.json

I added a sequence diagram for the v1/remediations/:plan_id/playbook_runs/:run_id endpoint.

RHINENG-16337: sequence diagram for GET v1/remediations/:plan_id/playbook_runs/:run_id

---

src/remediations/controller.read.js

RHINENG-13936: Ensure playbook runs are sorted by created_at

---

doc/diagrams/v1/remediations/{plan_id}/playbook_runs/getSystems.md
doc/responses/remediations/single_playbook_run_systems.json

Created sequence diagram for:
`GET remediations/:id/playbook_runs/:run_id/systems`

RHINENG-16338: Added sequence diagram for GET remediations/:id/playbook_runs/:run_id/systems

---

doc/diagrams/v1/remediations/{plan_id}/playbook_runs/getSystemDetails.md
doc/responses/remediations/playbook_run_host.json

Created sequence diagram describing `GET /remediations/:id/playbook_runs/:run/systems/:system` endpoint behavior.

RHINENG-16339: Added sequence diagram for GET /remediations/:id/playbook_runs/:run/systems/:system

---

doc/diagrams/v1/remediations/{plan_id}/playbook_runs/getRunDetails.md
doc/diagrams/v1/remediations/{plan_id}/playbook_runs/getSystemDetails.md
doc/diagrams/v1/remediations/{plan_id}/playbook_runs/getSystems.md
doc/diagrams/v1/remediations/{plan_id}/playbook_runs/listPlaybookRuns.md

Minor formatting updates to sequence diagrams.

Updated sequence diagram formatting

---

src/api/openapi.yaml

Added a new `DELETE /remediations/:id/issues` endpoint for bulk issue removal to openAPI spec.

RHINENG-17268: Added issue bulk delete endpoint to api spec.

---

src/api/openapi.yaml
src/remediations/routes.js

RHINENG-17360: Add GET /remediations/:id/status to api spec

---

src/api/openapi.yaml
src/remediations/__snapshots__/write.integration.js.snap
src/remediations/controller.write.js
src/remediations/routes.js
src/remediations/write.integration.js

Added a new bulk `DELETE /remediations/:id/systems` endpoint

RHINENG-16700: Add `DELETE /remediations/:id/systems` bulk delete endpoint

---

src/middleware/openapi/index.js

Bug Fixes:
- Corrected middleware to return JSON validation errors instead of silently processing them

RHINENG-17818: Fixed error that masked JSON validation errors
