RedHatInsights/insights-remediations

src/connectors/compliance/mock.js, src/connectors/ssg/mock.js, src/connectors/ssg/mock/standard/rsyslog_remote_loghost.yml, src/generator/__snapshots__/ssg.integration.js.snap, src/generator/factories/ComplianceFactory.js, src/generator/ssg.integration.js
An initial attempt to disable resolutions of rule rsyslog_remote_loghost for all RHEL versions and profiles.
CC @aleccohan @jharting 
Testing with Compliance locally (`false` means no remediation available):
```rb
JSON.parse(RemediationsAPI.new(Account.first).send(:remediations_response, Rule.where(ref_id: 'xccdf_org.ssgproject.content_rule_rsyslog_remote_loghost')).body)
=> {"ssg:rhel8|hipaa|xccdf_org.ssgproject.content_rule_rsyslog_remote_loghost"=>false,
"ssg:rhel7|c2s|xccdf_org.ssgproject.content_rule_rsyslog_remote_loghost"=>false,
"ssg:rhel8|cui|xccdf_org.ssgproject.content_rule_rsyslog_remote_loghost"=>false,
"ssg:rhel7|hipaa|xccdf_org.ssgproject.content_rule_rsyslog_remote_loghost"=>false, …
```
=> fix(ssg): RHICOMPL-1168 provides no remediation for rsyslog_remote_loghost

src/generator/__snapshots__/advisor.unit.js.snap, src/generator/__snapshots__/generator.unit.js.snap, src/generator/__snapshots__/vulnerabilities.unit.js.snap, src/remediations/__snapshots__/playbook.integration.js.snap, src/remediations/playbook.integration.js, src/templates/static/special/diagnosis.yml
Updated default Advisor diagnosis template to fix issue in this bugzilla.  Turns out the Regex needed to be slightly changed to acomodate for the whitespace character as well as the variable needing to be changed.    
Bugzilla in question: https://bugzilla.redhat.com/show_bug.cgi?id=1925655
JIRA: https://issues.redhat.com/browse/RHCLOUD-12216
=> RHCLOUD-12216: Advisor template fails with unexpected templating

db/seeders/20190107133125-tests-read-single.js, src/connectors/inventory/impl.js, src/connectors/inventory/impl.unit.js, src/connectors/inventory/mock.js, src/connectors/inventory/xjoin.js, src/connectors/inventory/xjoin.queries.js, src/connectors/inventory/xjoin.unit.js, src/remediations/__snapshots__/read.integration.js.snap, src/test/index.js
Added getSystemProfileBatch() to both inventory impl() as well as xjoin implementations.  This is going to be used for an additional check wrt adding cert auth to remediations /playbook endpoint.
=> RHCLOUD-12591: Add getSystemProfileBatch() to inventory impl

src/api/openapi.yaml, src/config/index.js, src/connectors/inventory/impl.js, src/connectors/inventory/impl.unit.js, src/connectors/inventory/mock.js, src/connectors/inventory/xjoin.queries.js, src/connectors/inventory/xjoin.unit.js, src/probes.js, src/remediations/__snapshots__/fifi.integration.js.snap, src/remediations/fifi.integration.js, src/remediations/fifi.js, src/remediations/remediations.format.js
The purpose of this PR is to modify the current Remediations FiFi pipeline to send RHC registered systems in a work request to the playbook-dispatcher without disturbing the pipeline that is already in place.  
To that end, the way that the pipeline works now is that instead of having a sole executor at the end of the "Preflight Check" that are not runnable due to being "Direct Connect" we now comb through these systems to see if they have an existing "rhc_client_id" if they do they are added to an executor that is marked as "connected" with the type "RHC".  All other systems (without an existing "rhc_client_id" are put in a seperate executor which will show up with an error stating that they cannot be run with FiFi.  
Additionally with these changes I had to modify one of the existing …
=> RHCLOUD-12760: Modify Remediations to include RHC compatability

src/remediations/__snapshots__/read.integration.js.snap, src/remediations/controller.read.js
Update the `/remediation` list function to also filter on issues that don't have the "details" section.  This "should" allow the issue_count variable in both the `/remediations` method as well as the `/remediations/:id` method to always be the same.
JIRA:  https://issues.redhat.com/browse/RHCLOUD-11059
=> RHCLOUD-11059: Remediation issues count not being displayed correctly

src/connectors/dispatcher/impl.js, src/connectors/dispatcher/impl.unit.js, src/connectors/dispatcher/mock.js
Updated playbook dispatcher connector to have additional endpoints for pulling current information about running jobs.  Specificly the 'dispatcher/v1/run_hosts' endpoint and the 'dispatcher/v1/runs' endpoint which will be used / configured with the current FiFi endpoints to fetch information about direct-connect jobs.
JIRA: https://issues.redhat.com/browse/RHCLOUD-13324    
=> RHCLOUD-13324: Update dispatcher-connector with new API endpoints

db/seeders/20191223133315-fifi.js, src/api/openapi.yaml, src/connectors/inventory/mock.js, src/remediations/__snapshots__/fifi.integration.js.snap, src/remediations/controller.fifi.js, src/remediations/fifi.integration.js, src/remediations/fifi.js
Now that the new smartManagement / marketplace check is in use the "run playbook" pipeline must make use of the "is_marketplace" field to only run playbooks on systems that have the "is_marketplace" field set to true (unless of course the customer has the smart_management entitlement.
JIRA: https://issues.redhat.com/browse/RHCLOUD-13082
=> RHCLOUD-13082: Update playbook generation pipeline to use marketplace logic

src/api/openapi.yaml, src/remediations/controller.fifi.js, src/remediations/fifi.integration.js, src/remediations/routes.js
Create /remediation/:id/executable endpoint for FE.  This endpoint check to see if there are any smart_management systems in a specific remediation OR if the smart_management entitlement is declared.
JIRA: https://issues.redhat.com/browse/RHCLOUD-13607    
=> RHCLOUD-13607: Create /executable endpoint for FE

src/remediations/__snapshots__/fifi.integration.js.snap, src/remediations/fifi.js
RHCLOUD-13852: Add additional states to pre-flight check.  These states are to designate which Direct connected systems are "regular" RHC systems and which are "Marketplace" systems.
JIRA:  https://issues.redhat.com/browse/RHCLOUD-13852
=> RHCLOUD-13852: Add additional states to pre-flight check

src/generator/__snapshots__/ssg.integration.js.snap, src/remediations/playbook/__snapshots__/playbook.integration.js.snap, src/remediations/playbook/playbook.integration.js, src/resolutions/resolvers/SSGResolver.js, src/resolutions/resolvers/SSGResolver.unit.js
Due to the recent move from the remediations vendored playbooks-ssg service to the compliance-ssg service vendored by compliance a few changes needed to be made to the playbook generation logic.  Firstly, the logic that defaults to using the"all" template is no longer necessary since compliance should be in charge of making sure all issues are available when queried.  
Additionally with the inclusion of playbook signatures two pieces of logic have been changed to allow for the validation to work.  
1.  Removed the auto-inclusion of the "insights_reboot_handler" due to the fact that the compliance team is now in-charge of adding this to their templates.
2.  Fixed an Issue I was seeing with the signature after the template was loaded and dumped using the "js-yaml" library.  Currently in …
=> RHCLOUD-15194 & RHCLOUD-15203 Compliance ssg template generation changes

deployment/clowdapp.yml
This is a quickfix for the Remediations Clowdapp.yml file based on the recent deprecation of the "web: true" field.  A change was made to add in the new format, i.e. webServices/public/enabled.  This PR fixes an indentation problem that caused an outage in STAGE yesterday.
=> QUICKFIX: fix webServices public enabled field indentation

src/remediations/fifi.js
RHCLOUD-19293: Fix Playbook Dispatcher error with pre-flight check.
Due to the error where a satellite_instance_id is not being set in the facts field in inventory there is an interaction that is currently breaking the pre-flight check.  This check should fix the logic to show the status as per-usual.
=> RHCLOUD-19293: Fix Playbook Dispatcher error with pre-flight check

src/connectors/dispatcher/impl.js, src/connectors/dispatcher/impl.unit.js
As it happens the pre-flight check is currently failing because of a logic issue in the dispatcher-connector inside of remediations.  There was an added layer object layer that was being checked for which was throwing the whole RHC-ConnectionStatus operation off.  It should now be resolved.    
=> [QUICKFIX] Update dispatcher-connector to fix pre-flight issue

deployment/clowdapp.yml
This PR just adds 1 line: `apiPath: remediations` to the public web service for the API in the ClowdApp.
=> Add apiPath to api public web service

deployment/clowdapp.yml
We do not have this secret available in all environments so it should be made optional
=> fix: Make the psk-playbook-dispatcher secret optional

src/config/index.js
Tested out on an elasticache with ssl enabled - listing keys:
```
null
[14:21:25.666] INFO (remediations/7): redis enabled
[14:21:25.725] INFO (remediations/7): connected to redis
[
'celery',
'_kombu.binding.celery.pidbox',
'_kombu.binding.celery',
'_kombu.binding.celeryev'
]
```
=> Enable support for using redis over SSL when password is present

deployment/clowdapp.yml
This PR adds the `FLOORIST_DISABLED` parameter to the `clowdapp.yml`. This adds the ability to disable the creation of the Floorist Job, in its entirety, within ephemeral/alternative environments.
The `FLOORIST_DISABLED` parameter ensures that Floorist Container is not built in a more restrictive environment, as opposed to using `FLOORIST_SUSPEND`, in which the container is still created but not run. 
Creating and not running the Floorist Container still add to the list of images that must be monitored/maintained for vulnerability management.
- Default Value: `FLOORIST_DISABLED: 'False'`
=> Adding FLOORIST_DISABLED Parameter to clowdapp.yml

src/remediations/controller.fifi_2.js
While debugging a playbook dispatcher API problem I found missing 'await's when calling async function.
=> Added missing await's

src/remediations/fifi.js
Added code to extract inventory id from label attached to rhc-direct run requests (until RHCLOUD-30669 is resolved)
=> RHINENG-7766: Added workaround for missing inventory ids

src/connectors/patchman/impl.js, src/remediations/fifi.integration.js, src/remediations/routes.js
RHINEG-7902: Patch deprecated their V1 and V2 endpoints so the Remediations app need to switch to the V3 api endpoints.
=> Move to Patch V3 api

src/config/index.js
Lower the default page limit for Vulnerability APIs to the max allowed value of 100 items per page.
RHINENG-8207
=> fix: default page limit for vuln

src/remediations/__snapshots__/fifi.integration.js.snap, src/remediations/fifi.integration.js, src/remediations/routes.js
Playbook-dispatcher updates are still not in production so I'm parking the code changes that depend on that so we can continue to deploy other code.
=> Temporarily switch back to old version of the code to unblock deployments

.github/dependabot.yml
Make dependabot run on Sundays so we can schedule any updates for the week on Monday mornings.
=> Configure dependabot to check for updates on Sunday

src/remediations/remediations.queries.js
src/remediations/remediations.queries.js(loadDetails) excludes issues with 0 systems, which can lead to a remediation being excluded, which leads to a db query returning fewer rows than expected.  Code was adjusted to accommodate the missing row(s).
=> RHINENG-8757: Fixed issue with db query returning fewer rows.

build/docker-compose-unit_test.yml, build/docker-compose.yml
postgresql-rds "-1" images are being deprecated; moving to postgresql-rds:14 instead.
=> refactor(dev): update postgresql-rds image tag

build/Dockerfile
Upgrading node and npm necessitated creating a user with a home directory (for npm to function).  Just setting the HOME envar is sufficient, however, so let's do that instead.
=> RHINENG-9557: Avoid creating a user in our image (use HOME envar instead)

src/api/openapi.yaml, src/remediations/write.integration.js
Don't allow leading/trailing whitespace in remediation plan names to avoid plans with names like "test" and "test ".
=> RHINENG-9812: Don't allow leading/trailing whitespace in plan name

src/util/trace.js
Something is creating messages so large clowdwatch is blowing up.  Turning off tracing for now to see if that's the source...
=> Disable tracing to see if it's the source of the overly large messages

src/util/log.js
Try catching pino-cloudwatch errors to see if we can keep from torpedoing our pods...
=> Added pino transport error handler to catch pino-cloudwatch errors

gulpfile.js
This PR moves noop module to the prod image files so that it is included in the prod build along with the test build. This is to avoid the following error when deploying when noop is required:
```
Error: Cannot find module './noop'
```
=> Update add noop to prod build.

src/api/openapi.yaml, src/remediations/write.integration.js
Relax the leading/trailing whitespace restrictions until we can fix the handful of database entries with "invalid" names.
=> Relax openapi remediation plan name restrictions pending db updates

db/migrations/20240502174415-fix-invalid-plan-names.js, src/util/log.js
The recent db migration left several remediation plans with names of the form " - 1"...  Rename these to "Blank - 1", etc.
=> RHINENG-9857: Update remediation plans with invalid names.

db/migrations/20240514205117-trim-tabs-from-plan-names.js
There were a few plans with leading or trailing tab characters in their names that we missed in the previous migration.  This migration will clean those up.
=> RHINENG-10058: Adding migration to remove leading / trailing tabs characters from plan names.

src/api/openapi.yaml
GET /remediations returns one of two objects:
* RemediationList
* RemediationNameList
The openapi-generator-cli v7.6.0 python binding generator generates a distinct schema for each of these objects. When decoding a response, the bindings will attempt to match the response to each of these schemas, in the same order as given in the spec file.
RemediationNameList is a strict subset of RemediationList. If the response is matched against these schemas in this order, then the first comparison will always succeed, and the first type of object will always be returned. This is problematic.
Fix: https://issues.redhat.com/browse/RHINENG-10796
=> Reorder anyOf statements

deployment/clowdapp.yml, src/config/__snapshots__/config.unit.js.snap, src/config/index.js, src/connectors/ssg/impl.js
Compliance playbook generation as failing once a remediation plan contained enough issues and systems.  This was caused by rate-limiting of the internal SSG playbook service and inefficient playbook generation code.
Resolved by cacheing compliance playbook snippets.
=> RHINENG-11246: Compliance playbook downloads failing

src/remediations/remediations.queries.js
Cert auth identities have no username.  The validation code for cached remediation plans was expecting the plan, which HAS an associated username since it was created via the UI, to match "null" and returning a null for the fetched plan, causing playbook downloads to work on the first try but fail on subsequent attempts (once the remediation plan has been cached).
=> RHINENG-12150: Fixed user check for cached remediation plans when using cert auth

src/remediations/controller.read.js, src/remediations/remediations.queries.js
The remediation plan query used by the playbook download endpoint included a sub-query to count resolved issues, which is rather inefficient.  Since this value is never used, a parameter was added to remove it from the query for this code path.
=> RHINENG-12281: Removed resolved issue count subquery from playbook download code

deployment/clowdapp.yml, src/config/index.js
`advisor-backend` is the correct clowd app name to grab the API service
endpoint.
[RHINENG-13051](https://issues.redhat.com/browse/RHINENG-13051)
=> Fix advisor host from clowder

.cleanmodules, build/Dockerfile, package-lock.json, package.json
Adding clean-modules to build process to remove extraneous package files (e.g. sample code causing vulnerability hits).
This is currently removing 6963 extraneous files...
=> RHINENG-13680: Add npm clean-modules to cleanup files

package-lock.json, package.json
Vulnerable version of semver was 5.7.0 so bumped it to the fixed version which is 5.7.2.
=> RHINENG-15288: Bump semver to 5.7.2

package-lock.json
We attempted this in this PR: https://github.com/RedHatInsights/insights-remediations/pull/571
But I guess it wasn't successful because the vulnerability showed up again in the January Fedramp scan :/ 
=> RHINENG-15273: Bump cross-spawn to 7.0.6

package-lock.json, package.json
Kind of a test PR for now. I want to see if we can bump `tough-cookie` to 4.1.4 which would fix our last vulnerability. `tough-cookie` is a dependency of `request-promise@4.2.6` and `request@2.88.2` and technically the version of `tough-cookie` that they require is ^2.3.3  and ~2.5.0. But overriding the version to ^4.1.3 might be fine...
=> RHINENG-15449: Bump tough-cookie to 4.1.4

build/Dockerfile, package.json
The multistage Dockerfile wasn't calling clean-modules during the dist build stage, resulting in all the extraneous items not getting removed from the prod image.
=> RHINENG-16576: Fix npm clean-modules build boo boo

package-lock.json, package.json
prismjs is listed as a direct dependency, which is causing problems with updates.  I'm removing it and letting npm sort out the details...
=> RHINENG-16923: remove prismjs as a direct dependency

src/api/openapi.yaml
Didn't remove the 'pending' status here because this breaks a lot of tests so I was thinking we could create a separate subtask for this?
`deepObject` and `explode: true` determine how query parameters are formatted so this allows for a filter like this:
```
?filter[name]=example-remediation&filter[status]=completed
```
If a plain string is passed, it's interpreted as a name search:
```
?filter=example-remediation
```
=> RHINENG-16796: Add sorting/filtering options to API spec

src/api/openapi.yaml
As a matter of policy we should explicitly list all properties allowed for an `object` and set `additionalProperties: false`
=> RHINENG-17235: Added missing 'additionalProperties: false' statement

src/api/openapi.yaml
Changed the description to make it clear that the path parameter is actually the system `insights_id`...
=> RHINENG-15979: Fixed description of `GET /diagnosis/:insights_id` endpoint

src/api/openapi.yaml
Just a few minor tweaks to satisfy our overly pedantic openAPI spec linter...
=> RHINENG-9347: Fixed pendantic yaml linter warnings
